### ISSUE TITLE
中文字符转换为URL编码

### ISSUE THREAD

**Issue by xyblue135** [ostoe/Ob-ImagePastePlugin#1]
在obsidian上使用此插件的时候,中文字符过长的话(也不知道是不是过长的问题)会出现 URL 编码的问题,也能正确解析到,但是看着不太舒服.

![微信图片_20231211013826](https://github.com/ostoe/Ob-ImagePastePlugin/assets/127581667/a81bc304-5ef6-4f16-a0c1-ddfacd02f590)
![123456](https://github.com/ostoe/Ob-ImagePastePlugin/assets/127581667/613dd2b1-7691-4ed8-bb33-e43cdcd98c7c)

**Comment by xyblue135** [comment]
貌似是一些符号的问题?

**Comment by ostoe** [comment]
> 貌似是一些符号的问题?

这里做了url转码为了更好的兼容性，我之前在windows和macos之间同步文件的时候遇到过特殊字符兼容性问题，我看看这几天把这个功能更新到可选配置项里面吧

**Comment by ostoe** [comment]
> 貌似是一些符号的问题?

已更新相关功能，请copy至插件目录or等待官方审核后更新[release 0.1.1](https://github.com/ostoe/Ob-ImagePastePlugin/releases/tag/0.1.1)
