### ISSUE TITLE
Suggest adding the ability to set a custom save location for images.

### ISSUE THREAD

**Issue by BetterDefender** [ostoe/Ob-ImagePastePlugin#2]
Generating a folder with the same name in the current directory will make the notes directory more cluttered. Suggest adding the ability to set the images to save in a custom location, thanks!

**Comment by ostoe** [comment]
Thanks for your suggestion, I will add this feature if I have time in the next few days.

**Comment by ostoe** [comment]
> Generating a folder with the same name in the current directory will make the notes directory more cluttered. Suggest adding the ability to set the images to save in a custom location, thanks!

I have added a setting to select the storage location. Please wait for the official review before updating, or manually copy main to the relevant directory. If you have any questions, please contact me.

**Comment by scil** [comment]
`tocustom: "Copy image to custom folder"`  this options does not work , and after restarting obsidian, this options reset.

**Comment by scil** [comment]
> `tocustom: "Copy image to custom folder"` this options does not work , and after restarting obsidian, this options reset.

I set the `CustomPath` to an absolute dir, not relative.

i commented out this `if`, and the custom folder works
```

      case "tocustom":
       // if (this.settings.CustomPath.startsWith("./")) {
          if (this.settings.CustomPath.contains("${filename}")) {
            dirPath = this.settings.CustomPath.replace(/\$\{filename\}/g, mdFile.basename);
          } else {
            dirPath = this.settings.CustomPath;
          }
          break;
     // }

```

finally, I add a new var `pathname`

```
      case "tocustom":
//        if (this.settings.CustomPath.startsWith("./")) {
          if (this.settings.CustomPath.contains("${")) {
              if (this.settings.CustomPath.contains("${filename}")) {
                dirPath = this.settings.CustomPath.replace(/\$\{filename\}/g, mdFile.basename);
                }
              else if (this.settings.CustomPath.contains("${filepath}")) {
                // extract   'articles/col1/article'  from  'articles/col1/article.md'
                const path =  mdFile.path.substring(0, mdFile.path.length  - mdFile.extension.length -1)
                dirPath = this.settings.CustomPath.replace(/\$\{filepath\}/g, path);
                }
          } else {
            dirPath = this.settings.CustomPath;
          }
          break;
        // }
```

If set custom path to  `/Attachments/${filepath}`,  for fir dir structure 
```
- Articles
  - Season1
    - 1.md
    - 2.md
```

it can produce dir like this

```
- Attachments
  - Articles
    - Season1
      - 1
        - 1.1.jpg
        - 1.2.jpg
      - 2
        - 2.1.jpg
        - 2.2.jpg
```



@ostoe  could you please accept this to source code?

**Comment by ostoe** [comment]
> > `tocustom: "Copy image to custom folder"` this options does not work , and after restarting obsidian, this options reset.
> 
> I set the `CustomPath` to an absolute dir, not relative.
> 
> i commented out this `if`, and the custom folder works
> 
> ```
> 
>       case "tocustom":
>        // if (this.settings.CustomPath.startsWith("./")) {
>           if (this.settings.CustomPath.contains("${filename}")) {
>             dirPath = this.settings.CustomPath.replace(/\$\{filename\}/g, mdFile.basename);
>           } else {
>             dirPath = this.settings.CustomPath;
>           }
>           break;
>      // }
> ```
> 
> finally, I add a new var `pathname`
> 
> ```
>       case "tocustom":
> //        if (this.settings.CustomPath.startsWith("./")) {
>           if (this.settings.CustomPath.contains("${")) {
>               if (this.settings.CustomPath.contains("${filename}")) {
>                 dirPath = this.settings.CustomPath.replace(/\$\{filename\}/g, mdFile.basename);
>                 }
>               else if (this.settings.CustomPath.contains("${filepath}")) {
>                 // extract   'articles/col1/article'  from  'articles/col1/article.md'
>                 const path =  mdFile.path.substring(0, mdFile.path.length  - mdFile.extension.length -1)
>                 dirPath = this.settings.CustomPath.replace(/\$\{filepath\}/g, path);
>                 }
>           } else {
>             dirPath = this.settings.CustomPath;
>           }
>           break;
>         // }
> ```
> 
> If set custom path to `/Attachments/${filepath}`, for fir dir structure
> 
> ```
> - Articles
>   - Season1
>     - 1.md
>     - 2.md
> ```
> 
> it can produce dir like this
> 
> ```
> - Attachments
>   - Articles
>     - Season1
>       - 1
>         - 1.1.jpg
>         - 1.2.jpg
>       - 2
>         - 2.1.jpg
>         - 2.2.jpg
> ```
> 
> @ostoe could you please accept this to source code?

Thanks for your suggestion, I will merge the code later.

**Comment by ostoe** [comment]
I released version 0.1.2. Where `CustomPath` uses a relative path startwith `./xxxxx` and uses a path relative to the relative workspace. The setting is startwith `xxxx`. Now the last setting will be **auto saved** after restarting the software.

update code
```js
case "tocustom":
				if (this.settings.CustomPath.startsWith("./") ) {
					// const filenameDirPath = mdFile.parent?.path ? path.join(mdFile.parent!.path, mdFile.basename) : mdFile.basename;
					if (this.settings.CustomPath.contains("${filename}")) {
						const relativeCustomPath =  this.settings.CustomPath.replace(/\$\{filename\}/g, mdFile.basename)
						dirPath = mdFile.parent?.path ? path.join(mdFile.parent!.path, relativeCustomPath) : relativeCustomPath;
						// dirPath = this.settings.CustomPath.replace(/\$\{filename\}/g, mdFile.basename)
					} else {
						
						dirPath = mdFile.parent?.path ? path.join(mdFile.parent!.path, this.settings.CustomPath) : this.settings.CustomPath;
					}
				} else {
					dirPath = this.settings.CustomPath
				}
				break;
```

**Comment by scil** [comment]
@ostoe thank you!

could you add support `${filepath}`  so the dir structure could be kept?

**Comment by ostoe** [comment]
> @ostoe thank you!
> 
> could you add support `${filepath}` so the dir structure could be kept?

You can try it, now filename and filepath are equivalent.

**Comment by scil** [comment]
@ostoe  Really? Wonderful! you are genies!

And, could you let absolute path support `${filename}`?  Now, it's supported only when  `this.settings.CustomPath.startsWith("./") `

**Comment by ostoe** [comment]
> @ostoe Really? Wonderful! you are genies!
> 
> And, could you let absolute path support `${filename}`? Now, it's supported only when `this.settings.CustomPath.startsWith("./") `

Now，you can use ${filename}  or ${filepath} as the key anyway，they are equivalent.

- IF set path start with './', it will set a relative current MDFile path."
- IF set path start without './, it will set a relative workspace root path."

**Comment by scil** [comment]
@ostoe 
Thank you ! however,  ${filename} not supported when path without './

```
case "tocustom":
				if (this.settings.CustomPath.startsWith("./") ) {
					.....
				} else {
                                         /****************
                                         ${filename} not processed here
                                         ************/
					dirPath = this.settings.CustomPath
				}
				break;
```

**Comment by ostoe** [comment]
```js
	case "tocustom":
		let replacePath: string;
		if (this.settings.CustomPath.contains("${filename}")) {
			replacePath = this.settings.CustomPath.replace(/\$\{filename\}/g, mdFile.basename)
		} else if (this.settings.CustomPath.contains("${filepath}")) { 
			replacePath = this.settings.CustomPath.replace(/\$\{filepath\}/g, mdFile.basename)
		} else {
			replacePath = this.settings.CustomPath;
		}
		if (this.settings.CustomPath.startsWith("./")) { 
			dirPath = mdFile.parent?.path ? path.join(mdFile.parent!.path, replacePath) : replacePath;
		} else {
			dirPath = replacePath;
		}
		break;
```

Oh my gosh, I'm so stupid, I just fixed it, thank you very much for your advice!!! !
